name: php-framework
recipe: lemp
config:
  via: nginx
  config: 
     vhosts: .lando/nginx.conf
  php: '8.2'
  database: postgres
  password: 83312
  portforward: 5432
  user: postgres
  webroot: public
